python:
  python
data:
  /home/ps/ForecastPlatform
dataprocess:
  /home/ps/ForecastPlatform/DataProcess
webdriver:
  "/home/ps/apps/webdriver/geckodriver"

spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:${dataprocess}/Forcasting.db
      driver-class-name: org.sqlite.JDBC
    nc:
      jdbc-url: jdbc:sqlite:${dataprocess}/NC.db
      driver-class-name: org.sqlite.JDBC
    meteorology:
      jdbc-url: jdbc:sqlite:${dataprocess}/Clawing/Meteorology.db
      driver-class-name: org.sqlite.JDBC

stations:
  ${dataprocess}/station.json
Typhoon:
  ${dataprocess}/Clawing/typhoon.json

updateData:
  ${dataprocess}/UpdateData.py
updateManData:
  ${dataprocess}/UpdateManData.py

clawingCloud:
  ${dataprocess}/Clawing/Cloud.py
clawingRadar:
  ${dataprocess}/Clawing/Radar.py
clawingRainfall:
  ${dataprocess}/Clawing/Rainfall.py
clawingRainfallpre:
  ${dataprocess}/Clawing/Rainfall_pre.py
clawingTyphoon:
  ${dataprocess}/Clawing/Typhoon.py
deleteClawingData:
  ${dataprocess}/Clawing/DeleteData.py

meteorology:
  file:
    cloud:
      "${data}/气象产品/卫星云图"
    radar:
      "${data}/气象产品/雷达拼图"
    rainfall:
      "${data}/气象产品/降水量实况"
    rainfallpre:
      "${data}/气象产品/降水量预报"
  db:
    "${dataprocess}/Clawing/Meteorology.db"


DataProcessLog:
  ${dataprocess}/logfile.log

TxtBuilder4zeta:
  ${dataprocess}/FieldProcess/txtBuilder4zeta.py
Triangle:
  ${dataprocess}/FieldProcess/triangle.py
FlowField:
  "${data}/Field/Flow"
WindField:
  "${data}/Field/Wind"
AddField:
  "${data}/Field/Add"

TyphoonUrl:
  http://typhoon.zjwater.gov.cn/