spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Forcasting.db
      driver-class-name: org.sqlite.JDBC
    nc:
      jdbc-url: jdbc:sqlite:D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/NC.db
      driver-class-name: org.sqlite.JDBC
    meteorology:
      jdbc-url: jdbc:sqlite:D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Meteorology.db
      driver-class-name: org.sqlite.JDBC

stations:
  "data/DataProcess/station.json"

python:
  D:/1tools/Miniconda/envs/Env1/python.exe
updateData:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/UpdateData.py

clawingCloud:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Cloud.py
clawingRadar:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Radar.py
clawingRainfall:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Rainfall.py
clawingRainfallpre:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Rainfall_pre.py
deleteClawingData:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/DeleteData.py

DataProcessLog:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/logfile.log

FlowField:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/Field/Flow
WindField:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/Field/Wind
AddField:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/Field/Add
TxtBuilder4flow:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/txtBuilder4flow.py
TxtBuilder4wind:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/txtBuilder4wind.py
TxtBuilder4zeta:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/txtBuilder4zeta.py
Triangle:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/triangle.py
DeleteFileData:
    D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/DeleteFileData.py