spring:
  application:
    name: station
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9999

mybatis:
  configuration:
    call-setters-on-nulls: true