python:
  C:/Users/22171/.conda/envs/Env1/python.exe
data:
  D:/1study/Work/2023_12_22_Storm/stormPerdiction/data
dataprocess:
  D:/1study/Work/2023_12_22_Storm/stormPerdiction/data/DataProcess
webdriver:
  "D:/1tools/chromedriver/chromedriver.exe"

spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:${dataprocess}/Forcasting.db
      driver-class-name: org.sqlite.JDBC
    nc:
      jdbc-url: jdbc:sqlite:${dataprocess}/NC.db
      driver-class-name: org.sqlite.JDBC
    meteorology:
      jdbc-url: jdbc:sqlite:${dataprocess}/Clawing/Meteorology.db
      driver-class-name: org.sqlite.JDBC

stations:
  ${dataprocess}/station.json
Typhoon:
  ${dataprocess}/Clawing/typhoon.json

updateData:
  ${dataprocess}/UpdateData.py

clawingCloud:
  ${dataprocess}/Clawing/Cloud.py
clawingRadar:
  ${dataprocess}/Clawing/Radar.py
clawingRainfall:
  ${dataprocess}/Clawing/Rainfall.py
clawingRainfallpre:
  ${dataprocess}/Clawing/Rainfall_pre.py
clawingTyphoon:
  ${dataprocess}/Clawing/Typhoon.py
deleteClawingData:
  ${dataprocess}/Clawing/DeleteData.py

meteorology:
  file:
    cloud:
      "${data}/气象产品/卫星云图"
    radar:
      "${data}/气象产品/雷达拼图"
    rainfall:
      "${data}/气象产品/降水量实况"
    rainfallpre:
      "${data}/气象产品/降水量预报"
  db:
    "${dataprocess}/Clawing/Meteorology.db"


DataProcessLog:
  ${dataprocess}/logfile.log

DeleteFileData:
  ${dataprocess}/FieldProcess/DeleteFieldData.py
TxtBuilder4flow:
  ${dataprocess}/FieldProcess/txtBuilder4flow.py
TxtBuilder4wind:
  ${dataprocess}/FieldProcess/txtBuilder4wind.py
TxtBuilder4zeta:
  ${dataprocess}/FieldProcess/txtBuilder4zeta.py
Triangle:
  ${dataprocess}/FieldProcess/triangle.py
CppExecution:
  ${dataprocess}/FieldProcess/Debug/FlowField_Builder.exe
CppFlowFieldInputPath:
  "${dataprocess}/FieldProcess/output/Flow"
CppFlowFieldJsonPath:
  "${dataprocess}/FieldProcess/Debug_json/description_new_flow.json"
CppWindFieldInputPath:
  "${dataprocess}/FieldProcess/output/Wind"
CppWindFieldJsonPath:
  "${dataprocess}/FieldProcess/Debug_json/description_new_wind.json"
FlowField:
  "${data}/Field/Flow"
WindField:
  "${data}/Field/Wind"
AddField:
  "${data}/Field/Add"