python:
  python
data:
  /run/media/ps/c4cc18ff-fa71-43fb-8a59-06bc37d5c482/ForecastPlatform
dataprocess:
  /run/media/ps/c4cc18ff-fa71-43fb-8a59-06bc37d5c482/ForecastPlatform/DataProcess

spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:${dataprocess}/Forcasting.db
      driver-class-name: org.sqlite.JDBC

stations:
  ${dataprocess}/station.json
Typhoon:
  ${dataprocess}/Clawing/typhoon.json

updateData:
  ${dataprocess}/UpdateDataV2.py

DataProcessLog:
  ${dataprocess}/logfile.log

Script1Name:
  "downloadwaterlevelnow.sh"
Script2Name:
  "waterlevelnow1.sh"
DirectoryPath:
  "${data}"
ForecastDataPath:
  "${data}/forecastData"
ManuelUpdating:
  ${dataprocess}/UpdateDataV2_man.py