python:
  D:\1tools\Miniconda\envs\Env1
data:
  D:/1study/Work/2023_12_22_Storm/stormPerdiction/data
dataprocess:
  D:/1study/Work/2023_12_22_Storm/stormPerdiction/data/DataProcess

spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:${dataprocess}/Forcasting.db
      driver-class-name: org.sqlite.JDBC

stations:
  ${dataprocess}/station.json
Typhoon:
  ${dataprocess}/Clawing/typhoon.json

updateData:
  ${dataprocess}/UpdateDataV2.py


DataProcessLog:
  ${dataprocess}/logfile.log

Script1Name:
  "test.sh"
Script2Name:
  "run.sh"
DirectoryPath:
  "D:/1study/Work/2023_12_22_Storm/StormPerdiction/data"
ForecastDataPath:
  "${data}/forecastData"
ManuelUpdating:
  ${dataprocess}/UpdateDataV2_man.py