spring:
  application:
    name: station
  profiles:
    active: docker
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB

server:
  port: 9989

mybatis:
  configuration:
    call-setters-on-nulls: true