spring:
  datasource:
    level:
      jdbc-url: jdbc:sqlite:D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Forcasting.db
      driver-class-name: org.sqlite.JDBC
    nc:
      jdbc-url: jdbc:sqlite:D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/NC.db
      driver-class-name: org.sqlite.JDBC
    meteorology:
      jdbc-url: jdbc:sqlite:D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Meteorology.db
      driver-class-name: org.sqlite.JDBC

stations:
  "data/DataProcess/station.json"

python:
  C:/Users/22171/.conda/envs/Env1/python.exe
updateData:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/UpdateData.py

clawingCloud:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Cloud.py
clawingRadar:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Radar.py
clawingRainfall:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Rainfall.py
clawingRainfallpre:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/Rainfall_pre.py
deleteClawingData:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/Clawing/DeleteData.py

DataProcessLog:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/logfile.log

DeleteFileData:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/DeleteFieldData.py
TxtBuilder4flow:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/txtBuilder4flow.py
TxtBuilder4wind:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/txtBuilder4wind.py
TxtBuilder4zeta:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/txtBuilder4zeta.py
Triangle:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/triangle.py
CppExecution:
  D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/Debug/FlowField_Builder.exe
CppFlowFieldInputPath:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/output/Flow"
CppFlowFieldJsonPath:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/Debug_json/description_new_flow.json"
CppWindFieldInputPath:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/output/Wind"
CppWindFieldJsonPath:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/DataProcess/FieldProcess/Debug_json/description_new_wind.json"
FlowField:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/Field/Flow"
WindField:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/Field/Wind"
AddField:
  "D:/1study/Work/2023_12_22_Storm/stormPrediction/data/Field/Add"